### ISSUE TITLE
Add placeHolder image parameter to AnimatedImage.manager.loadImage method.

### ISSUE THREAD

**Issue by git-hwa** [kean/Nuke-AnimatedImage-Plugin#12]
It would be great if there is an parameter for placeHolder image in AnimatedImage.
Something like this.

`AnimatedImage.manager.loadImage(with: request, into: self, placeHolder: UIImage(named: "placeHolder"))`

**Comment by git-hwa** [comment]
And is there anyway to know if FLAnimatedImage is already cached or not?

**Comment by kean** [comment]
Hey @lubos08!

> It would be great if there is an parameter for placeHolder image in AnimatedImage.

I'm not sure whether placeholder would be that worthy of an addition, since you can just set it yourself:

``` swift
imageView.image = UIImage(named: "placeHolder")
Nuke.loadImage(with: url, into: imageView)
```

Or if you worry about performance:

``` swift
Nuke.loadImage(with: url, into: imageView)
if imageView.image == nil {
    imageView.image = UIImage(named: "placeHolder")
}
```

You can also add your own extension method to `Nuke.Manager` that has a placeholder parameter. 

I'd really prefer to keep Nuke's APIs as small and simple as possible. Maybe I'll later add a separate Nuke-Extensions repo with a bunch of extension methods like this.

**Comment by kean** [comment]
> And is there anyway to know if FLAnimatedImage is already cached or not?

For mem cache:

``` swift
if Cache.shared[Request(url: imageURL)] != nil {
    // image is in mem cache
}
```

For disk cache it's not that trivial.

**Comment by git-hwa** [comment]
@kean Thanks for your update.
